# Site settings
title: Blog
email: your-email@domain.com
description: "Blog"
baseurl: ""
url: "http://pablosajnovsky.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

